### ISSUE TITLE
If list view contains the header, item's number after click is not correct.

### ISSUE THREAD

**Issue by JohnKuper** [blandware/android-atleap#7]
Approximate solution:
mMenuListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    int posWithoutHeader = position - mMenuListView.getHeaderViewsCount();
                    selectMenuItem(posWithoutHeader);
                }
            });

**Comment by agrebnev** [comment]
Fixed
