### ISSUE TITLE
Add the ability to disable the drawer burger animation.

### ISSUE THREAD

**Issue by JohnKuper** [blandware/android-atleap#9]
Approximate solution:
@Override
    public void onDrawerSlide(View drawerView, float slideOffset) {
        if (drawerConfig.isAnimationOn) {
        super.onDrawerSlide(drawerView, slideOffset)
        } else {
        super.onDrawerSlide(drawerView, 0); // this disables the animation 
       }
    }

**Comment by agrebnev** [comment]
Fixed
